### PR TITLE
Fixed application wording consistency for "login"

### PR DESCRIPTION
**Pull request by ILL35T**
Guys this has really been bugging me for a while now and every project I start I have to scaffold identity just for the login page and then change "log in" to "login"
The _LoginPartial.cshtml refers to the page as "Login" so it should be consistent throughout and be called "Login".

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
image

**Comment by Rick-Anderson** [comment]
> The _LoginPartial.cshtml refers to the page as "Login" so it should be consistent throughout and be called "Login".

That's the one to change.

**Comment by HaoK** [comment]
Scaffolding is the wrong place to fix this first anyways, you would need to start with a PR against the aspnetcore bits...  @blowdart for his opinion since wording would be his call

**Comment by blowdart** [comment]
I'd go for login for now, and re-examine in 6.0 for sign-in.

**Comment by HaoK** [comment]
@ILL35T you will need to update the actual files in the product before updating scaffolding: https://github.com/dotnet/aspnetcore/tree/master/src/Identity/UI/src/Areas/Identity

**Comment by ILL35T** [comment]
@HaoK thanks, I have updated it here: https://github.com/dotnet/aspnetcore/pull/23931
I need someone to review it. @blowdart

**Comment by HaoK** [comment]
We aren't doing this for 5.0

**Pull request closed without merging**
