### PR TITLE
Port Identity UI accessibility fixes to scaffolding

### PR DESCRIPTION
**Pull request by HaoK**
Port of https://github.com/dotnet/aspnetcore/pull/29706

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks @HaoK.
I assume you just copied over the markup from the identity UI pages as is?

**Review by deepchoudhery — APPROVED** [review]
LGTM

**Comment by HaoK** [comment]
@mkArtakMSFT unfortunately the files aren't identical so its a bit of a manual port of the changes

**Comment by mkArtakMSFT** [comment]
Ok I think it's safe to merge given that it's a set of HTML only changes.

**Pull request merged**
