### PR TITLE
removed DotNet-Blob-Feed from yaml

### PR DESCRIPTION
**Pull request by deepchoudhery**
removing DotNet-Blob-Feed to fix build pipelines.

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by akoeplinger** [comment]
FYI you'll need to backport this to 6.0/7.0/8.0 branches.

**Comment by akoeplinger** [comment]
@deepchoudhery this still needs to be backported.

**Comment by akoeplinger** [comment]
@deepchoudhery FYI this is still missing from 7.0 and 6.0

**Comment by deepchoudhery** [comment]
> @deepchoudhery FYI this is still missing from 7.0 and 6.0

merged for [release/7.0](https://github.com/dotnet/Scaffolding/commit/2f465b7e0fd5521e71afd148ecd2407954576189) and [release/6.0](29669ff1b55efcb79e495886ff0fd24982f8ba01). tyty

**Pull request merged**
