### PR TITLE
Add tags to minimalapi endpoints templates

### LINKED ISSUE #1886: Minimal API scaffolding should include OpenAPI tags
Scaffolding multiple endpoints with the Minimal API scaffolder doesn't allow filtering by tags, and SwaggerUI view shows all endpoints in one long list.

I would like to see the `WithTags()` statement automatically added. While in the long term this may be solved by https://github.com/dotnet/aspnetcore/pull/41265, the current scaffolding experience should be improved.

I don't believe there is a way to apply the tags at the `IEndpointRouteBuilder ` level, so I would recommend we add `.WithTags(nameof(EndpointsClass))` before the `WithName()` call:

```csharp
public static class SpeakerEndpoints
{
    public static void MapSpeakerEndpoints (this IEndpointRouteBuilder routes)
    {
        routes.MapGet("/api/Speaker", async (ApplicationDbContext db) =>
        {
            return await db.Speakers.ToListAsync();
        })
        .WithTags(nameof(SpeakerEndpoints))
        .WithName("GetAllSpeakers");

        //other route mapping calls
    }
}
```

### PR DESCRIPTION
**Pull request by jongalloway**
- [x] The code builds and tests pass (verified by our automated build checks)
- [x] Commit messages follow this format
        Summary of the changes
        - Added `@:.WithTags(nameof(@modelName))` to the four minimalapi endpoint scaffolders when OpenAPI option is selected

Fixes #1886 - implementation as discussed in issue

- [x] Code meets the expectations our engineering guidelines.
      https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines

### CODE REVIEW

**Comment by jongalloway** [comment]
+ @deepchoudhery @halter73 @captainsafia
Look good?

**Review by captainsafia — APPROVED** [review]
LGTM for now! We can leverage route groups here once support for OpenAPI extension methods on route groups is in.

**Comment by deepchoudhery** [comment]
For future reference, would love to know what milestones are supported (extension methods maybe missing in .NET 6 packages/sdk or whatnot) so I'd know which servicings can include such updates. @jongalloway

**Comment by jongalloway** [comment]
@deepchoudhery - Gotcha. This one is fine to backport to .NET 6.

**Pull request merged**
